name: Randomly share a blog post.
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 14 * * *'

jobs:
  random-social-share:
    name: Randomly share a blog post.
    runs-on: ubuntu-latest
    steps:
      - uses: hendrixjoseph/random-social-share@master
        with:
          source: https://www.joehxblog.com/data/posts.csv
          twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          facebook_access_token: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
